name: Generate Contribution Snake
on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sallar/github-contribution-grid-snake-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
