name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: DUCANHTRA

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or update output branch
        run: |
          git checkout --orphan output
          git rm -rf .
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution snake SVG"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
